### ISSUE TITLE
Peer to Peer code review - Morning session

### ISSUE THREAD

**Issue by NitBravoA92** [HFG43/JS_Capstone#23]
Hi, @HFG43 👨‍💻  

### Congratulations! 🎉

You have really done an amazing job! 
Your code looks perfectly fine and works as expected. ⭐

## Highlights

✅ You used Gitflow correctly 👍
✅ Clean and understandable code 👍
✅ Using ES6 correctly👍
✅ API call correctly using Async functions 👍

# Optional suggestions: ♻️

We really appreciate your effort in implementing the different functionalities in your code, 🥇 however there are some suggestions that we have for you that can help you improve 🎁 the user experience 🤵 on your webpage: 

- [ ] We kindly suggest you have a search button to be able to filter and have the right movie selection or genre. This could be very helpful for users when looking for the series on the website.

**Comment by HFG43** [comment]
Thanks @NitBravoA92 for your feedback! I will work on your suggestions to improve user expierence! 👌👌😎
